#!/usr/bin/env python3
"""Run the six contract failure injections and record what the guard actually did.

The delivery contract names six injections that must each be refused. Asserting
that in prose would be the same defect this lane exists to correct, so the
receipt is generated by running them: each injection is passed to
`write_admission.admit` and the verdict it returns is written down, whatever it
is. If a future change makes one of them pass, this script says so.

The control case matters as much as the injections. It is a fully declared write
to `main`, and it must be ADMITTED — a guard that refused everything would pass
all six injections while being useless and would have reinstated the voided
category by other means.

    python3 produce_injection_receipt.py --out <path>
"""

from __future__ import annotations

import argparse
import copy
import hashlib
import importlib.util
import json
import sys
from datetime import datetime, timedelta, timezone
from pathlib import Path


TOOLS = Path(__file__).resolve().parents[1] / "tools"


def _load(name: str):
    spec = importlib.util.spec_from_file_location(name, TOOLS / f"{name}.py")
    module = importlib.util.module_from_spec(spec)
    assert spec.loader is not None
    sys.modules[name] = module
    spec.loader.exec_module(module)
    return module


wa = _load("write_admission")
rr = _load("reversal_rehearsal")


def _ago(seconds: int) -> str:
    return (datetime.now(timezone.utc) - timedelta(seconds=seconds)).strftime("%Y-%m-%dT%H:%M:%SZ")


def _manifest_evidence() -> dict:
    payload = b"deliverable bytes"
    entries = [{"path": "EXAMPLE.json", "size_bytes": len(payload),
                "sha256": hashlib.sha256(payload).hexdigest()}]
    bundle = hashlib.sha256(
        json.dumps(entries, sort_keys=True, separators=(",", ":")).encode("utf-8")).hexdigest()
    return {"asserts_result": True, "kind": "MANIFEST_CLOSURE",
            "record": {"entries": entries, "bundle_sha256": bundle},
            "present_paths": ["EXAMPLE.json"]}


PRE, POST = "a" * 40, "b" * 40


def control() -> dict:
    return {
        "declaration_version": "1.0",
        "declaration_id": "WD-INJECTION-CONTROL",
        "declared_by": "OE-W9-REASON-GATED-WRITES",
        "declared_at": _ago(60),
        "target": {"ref": "main", "paths": ["workstreams/so02/**"], "operation": "COMMIT_AND_PUSH"},
        "reason": {
            "code": "CORRECT_PUBLISHED_ERROR",
            "statement": ("The guard published on main refuses writes by target name, a category "
                          "the founder voided on 2026-08-23; correcting it on main is the correction."),
            "defect_reference": "protected-surface category voided by standing amendment 2026-08-23",
            "defect_observed_at": _ago(1800),
        },
        "reversal": {
            "method": "RESTORE_REF_TO_RECORDED_SHA",
            "recorded_sha": PRE, "post_write_sha": POST,
            "custody_ref": "refs/tags/pre-write/main-injection-control",
            "command": rr.build_reversal("RESTORE_REF_TO_RECORDED_SHA", "main",
                                         recorded_sha=PRE, post_write_sha=POST)["command"],
        },
        "evidence": _manifest_evidence(),
        "concurrency": {"observed_at": _ago(30), "ref_sha_at_observation": PRE,
                        "agents": [{"bcId": "bc-idle", "branchName": "main", "status": "IDLE"}]},
    }


def mutate(**overrides) -> dict:
    out = control()
    for dotted, value in overrides.items():
        keys = dotted.split(".")
        node = out
        for key in keys[:-1]:
            node = node[key]
        if value is None and dotted.count(".") == 0:
            node.pop(keys[-1], None)
        else:
            node[keys[-1]] = value
    return out


def drop(*paths) -> dict:
    out = control()
    for dotted in paths:
        keys = dotted.split(".")
        node = out
        for key in keys[:-1]:
            node = node[key]
        node.pop(keys[-1], None)
    return out


def injections() -> list[tuple[str, str, str, object]]:
    """(id, contract name, what was broken, declaration)"""
    lying = mutate(**{"reversal.command": ["git", "push", "origin", "main"]})
    lying["reversal"]["rehearsed"] = True
    lying["reversal"]["rehearsal_receipt"] = {"result": "REVERSAL_EXECUTED_AND_VERIFIED"}

    forged = control()
    forged["evidence"]["record"]["bundle_sha256"] = "0" * 64

    return [
        ("INJ-1", "an undeclared write",
         "no declaration supplied at all", {}),
        ("INJ-2A", "a write with an empty reason",
         "reason.statement is whitespace", mutate(**{"reason.statement": "   "})),
        ("INJ-2B", "a write with a vacuous reason",
         "reason.statement is portable boilerplate naming no target, and the reason code's "
         "required fields are absent",
         drop("reason.defect_reference", "reason.defect_observed_at") |
         {"reason": dict(drop("reason.defect_reference", "reason.defect_observed_at")["reason"],
                         statement="Making the necessary changes as instructed.")}),
        ("INJ-3", "a write with no reversal",
         "the reversal block is absent", drop("reversal")),
        ("INJ-4", "a reversal that does not actually reverse",
         "the command is hand-edited away from the constructor and the declaration claims it was "
         "rehearsed successfully", lying),
        ("INJ-5", "a write to a branch with a live run",
         "an agent in a non-settled state holds the target ref",
         mutate(**{"concurrency.agents": [
             {"bcId": "bc-live", "branchName": "main", "status": "RUNNING", "name": "another lane"}]})),
        ("INJ-6A", "a result-asserting write with no evidence",
         "the reason code asserts a result and the evidence block is absent", drop("evidence")),
        ("INJ-6B", "a result-asserting write whose evidence fails recomputation",
         "the manifest's bundle_sha256 does not bind its entries", forged),
    ]


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Produce the failure-injection receipt")
    parser.add_argument("--out", default=None)
    args = parser.parse_args(argv)

    results = []
    control_report = wa.admit(control(), Path("."), check_ref_movement=False)
    results.append({
        "id": "CONTROL",
        "contract_name": "a fully declared write to main",
        "expected": "ADMITTED",
        "verdict": control_report["verdict"],
        "failed_gates": control_report["failed_gates"],
        "as_expected": control_report["verdict"] == wa.ADMITTED,
        "why_it_matters": ("A guard that refused everything would pass all six injections while "
                           "being useless, and would have reinstated the voided category by other "
                           "means. main is an ordinary target and must be admitted when declared."),
    })

    for ident, name, broken, declaration in injections():
        report = wa.admit(declaration, Path("."), check_ref_movement=False)
        results.append({
            "id": ident,
            "contract_name": name,
            "what_was_broken": broken,
            "expected": "REFUSED",
            "verdict": report["verdict"],
            "failed_gates": report["failed_gates"],
            "refusals": [f for gate in report["gates"] for f in gate["findings"]
                         if gate["gate"] in report["failed_gates"]][:4],
            "as_expected": report["verdict"] == wa.REFUSED,
        })

    receipt = {
        "receipt_id": "OE-W9-FAILURE-INJECTIONS",
        "produced_at": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "evidence_label": "DIRECTLY_REPRODUCED",
        "how_to_reproduce": "python3 produce_injection_receipt.py",
        "generated_not_asserted": ("Each row is the verdict write_admission.admit actually returned "
                                   "for that declaration, recorded whatever it was."),
        "all_as_expected": all(row["as_expected"] for row in results),
        "results": results,
        "decision_changed": [],
    }
    text = json.dumps(receipt, indent=2, sort_keys=True)
    if args.out:
        Path(args.out).parent.mkdir(parents=True, exist_ok=True)
        Path(args.out).write_text(text + "\n", encoding="utf-8")
    print(text)
    return 0 if receipt["all_as_expected"] else 1


if __name__ == "__main__":
    sys.exit(main())
