"""PO03-WA-055 — three independent candidates ranked by a frozen executable rubric.

Frozen hypothesis: three independent candidates are rankable by a frozen
executable rubric.

The commission requires at least three independently generated candidates for a
consequential decision. Ranking them by narrative is where the requirement
usually dies: the scoring is reconstructed after the preferred answer is known.
This component makes the ranking mechanical and reproducible:

  * the rubric is content-addressed and the ranker refuses a digest mismatch;
  * fewer than three independent candidates is a refusal, not a low-confidence
    ranking;
  * candidates generated by the same principal or model family are not
    independent, and duplicates collapse;
  * a missing criterion score is NOT_SUPPORTED and lowers coverage rather than
    scoring zero;
  * ordering is invariant under input permutation, with declared deterministic
    tie-breaks;
  * pairwise dominance is reported so a ranking that is not Condorcet-consistent
    is visible instead of hidden behind a single total.

Standard library only.
"""

from __future__ import annotations

import hashlib
import itertools
import json
from dataclasses import dataclass, field

NOT_SUPPORTED = "NOT_SUPPORTED"
MIN_INDEPENDENT_CANDIDATES = 3


class RubricMismatch(RuntimeError):
    """Raised when the supplied rubric does not match its frozen digest."""


class InsufficientCandidates(ValueError):
    """Raised when fewer than three independent candidates are supplied."""


@dataclass(frozen=True)
class Criterion:
    key: str
    weight: float
    higher_is_better: bool = True

    def as_dict(self) -> dict:
        return {"key": self.key, "weight": self.weight, "higher_is_better": self.higher_is_better}


@dataclass(frozen=True)
class Rubric:
    rubric_id: str
    criteria: tuple

    def digest(self) -> str:
        payload = json.dumps(
            {"rubric_id": self.rubric_id, "criteria": [c.as_dict() for c in self.criteria]},
            sort_keys=True,
        )
        return hashlib.sha256(payload.encode()).hexdigest()

    def total_weight(self) -> float:
        return sum(c.weight for c in self.criteria)


@dataclass(frozen=True)
class Candidate:
    candidate_id: str
    principal: str
    model_family: str
    scores: dict = field(default_factory=dict)

    def content_key(self) -> str:
        return hashlib.sha256(
            json.dumps({"scores": self.scores}, sort_keys=True).encode()
        ).hexdigest()


@dataclass(frozen=True)
class Scored:
    candidate_id: str
    weighted_score: float
    coverage: float
    scored_criteria: int
    unsupported_criteria: tuple
    principal: str
    model_family: str

    def sort_key(self):
        # Deterministic total order: score desc, coverage desc, then id asc.
        return (-round(self.weighted_score, 12), -round(self.coverage, 12), self.candidate_id)


def _normalise(value, criterion: Criterion) -> float:
    if not isinstance(value, (int, float)) or isinstance(value, bool):
        raise TypeError(f"score for {criterion.key!r} must be numeric, got {value!r}")
    if not 0.0 <= float(value) <= 1.0:
        raise ValueError(f"score for {criterion.key!r} must lie in [0, 1], got {value!r}")
    return float(value) if criterion.higher_is_better else 1.0 - float(value)


def score_candidate(rubric: Rubric, candidate: Candidate) -> Scored:
    total, covered_weight, unsupported, scored = 0.0, 0.0, [], 0
    for criterion in rubric.criteria:
        raw = candidate.scores.get(criterion.key, NOT_SUPPORTED)
        if raw == NOT_SUPPORTED or raw is None:
            unsupported.append(criterion.key)
            continue
        total += criterion.weight * _normalise(raw, criterion)
        covered_weight += criterion.weight
        scored += 1
    weighted = total / covered_weight if covered_weight else 0.0
    coverage = covered_weight / rubric.total_weight() if rubric.total_weight() else 0.0
    return Scored(
        candidate.candidate_id,
        weighted,
        coverage,
        scored,
        tuple(sorted(unsupported)),
        candidate.principal,
        candidate.model_family,
    )


def independent_subset(candidates) -> list:
    """Drop duplicates by content and keep one candidate per principal."""
    seen_content, seen_principal, out = set(), set(), []
    for candidate in sorted(candidates, key=lambda c: c.candidate_id):
        content = candidate.content_key()
        if content in seen_content or candidate.principal in seen_principal:
            continue
        seen_content.add(content)
        seen_principal.add(candidate.principal)
        out.append(candidate)
    return out


def pairwise_dominance(scored) -> dict:
    """Report which candidate dominates which, so a cycle cannot hide in a total."""
    table = {}
    for a, b in itertools.combinations(scored, 2):
        if a.weighted_score > b.weighted_score:
            table[(a.candidate_id, b.candidate_id)] = a.candidate_id
        elif b.weighted_score > a.weighted_score:
            table[(a.candidate_id, b.candidate_id)] = b.candidate_id
        else:
            table[(a.candidate_id, b.candidate_id)] = "TIE"
    return table


def rank(rubric: Rubric, candidates, expected_digest: str, require_distinct_families: bool = True) -> dict:
    if rubric.digest() != expected_digest:
        raise RubricMismatch(
            f"rubric digest {rubric.digest()} does not match frozen {expected_digest}"
        )
    candidates = list(candidates)
    independent = independent_subset(candidates)
    if len(independent) < MIN_INDEPENDENT_CANDIDATES:
        raise InsufficientCandidates(
            f"{len(independent)} independent candidate(s) after de-duplication; "
            f"{MIN_INDEPENDENT_CANDIDATES} are required"
        )
    families = {c.model_family for c in independent if c.model_family}
    if require_distinct_families and len(families) < 2:
        raise InsufficientCandidates(
            f"candidates span only {sorted(families)}; a second frontier family is required"
        )

    scored = sorted((score_candidate(rubric, c) for c in independent), key=Scored.sort_key)
    ordering = [s.candidate_id for s in scored]
    dominance = pairwise_dominance(scored)
    condorcet_consistent = all(
        (dominance.get((a, b)) == a or dominance.get((a, b)) == "TIE")
        for i, a in enumerate(ordering)
        for b in ordering[i + 1 :]
    )
    ties = [
        (a.candidate_id, b.candidate_id)
        for a, b in itertools.combinations(scored, 2)
        if abs(a.weighted_score - b.weighted_score) < 1e-12
    ]
    return {
        "rubric_id": rubric.rubric_id,
        "rubric_digest": rubric.digest(),
        "ranking": ordering,
        "winner": ordering[0],
        "scored": [s.__dict__ for s in scored],
        "dropped_as_dependent": sorted(
            {c.candidate_id for c in candidates} - {c.candidate_id for c in independent}
        ),
        "model_families": sorted(families),
        "ties": ties,
        "tie_break_rule": "weighted score desc, coverage desc, candidate_id asc",
        "condorcet_consistent": condorcet_consistent,
        "decision_changed": [],
    }
