#!/usr/bin/env python3
"""Deterministic emitter and immutable-commit verifier for the PO-03 custody canary.

The canary artifact is derived only from the immutable task capsule, so the same
bytes can be regenerated by any reader.  Verification never trusts the working
tree: every byte compared here is read back out of a named commit object.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import subprocess
import sys
from pathlib import Path
from typing import Any


SLOT = "workstreams/po03/attempts/canary/po03-canary-001"
CAPSULE_INPUT = "workstreams/po03/control/tasks/po03-canary-001/input.json"
CAPSULE_ACCEPTANCE = "workstreams/po03/control/tasks/po03-canary-001/acceptance.json"
CANARY_PATH = f"{SLOT}/canary.json"
MANIFEST_PATH = f"{SLOT}/manifest.json"

CANARY_VERSION = "PO03-TRANSACTIONAL-CUSTODY-CANARY-v2"
MANIFEST_VERSION = "PO03-CANARY-MANIFEST-v2"
WORKER_ID = "po03-canary-001-producer"

MEDIA_TYPES = {
    ".json": "application/json",
    ".py": "text/x-python",
    ".txt": "text/plain; charset=utf-8",
}

DISPOSITIONS = {
    "readback.json": "SUPERSEDED_PRIOR_ATTEMPT_EVIDENCE",
}

PRIOR_ATTEMPT_COMMIT = "46080e21eec5766633b890c978fa5efdc53a3c94"
PRIOR_CANARY_SHA256 = "1da6899e982e0360580d6cefb4256a51b5b190bda5a1a42479dcc765b60a0831"


def git(repo: Path, *args: str) -> bytes:
    result = subprocess.run(
        ("git", "-C", str(repo), *args), check=True, capture_output=True
    )
    return result.stdout


def repo_root(start: Path) -> Path:
    return Path(git(start, "rev-parse", "--show-toplevel").decode("utf-8").strip())


def blob_at(repo: Path, ref: str, path: str) -> bytes:
    return git(repo, "cat-file", "blob", f"{ref}:{path}")


def tracked_at(repo: Path, ref: str, prefix: str) -> list[str]:
    raw = git(repo, "ls-tree", "-r", "-z", "--name-only", ref, "--", prefix)
    return sorted(item.decode("utf-8") for item in raw.split(b"\0") if item)


def sha256_hex(payload: bytes) -> str:
    return hashlib.sha256(payload).hexdigest()


def canonical_payload(obj: Any) -> bytes:
    return json.dumps(obj, sort_keys=True, ensure_ascii=False, separators=(",", ":")).encode("utf-8")


def canonical_document(obj: Any) -> bytes:
    return (json.dumps(obj, sort_keys=True, ensure_ascii=False, indent=2) + "\n").encode("utf-8")


def media_type_for(path: str) -> str:
    return MEDIA_TYPES.get(Path(path).suffix, "application/octet-stream")


def build_canary(input_bytes: bytes, acceptance_bytes: bytes) -> bytes:
    capsule = json.loads(input_bytes.decode("utf-8"))
    transaction = capsule["transaction"]
    nonce = capsule["canary_nonce"]

    payload = {
        "acceptance_contract_sha256": sha256_hex(acceptance_bytes),
        "attempt_number": transaction["attempt_number"],
        "canary_nonce": nonce,
        "canary_nonce_sha256": sha256_hex(nonce.encode("utf-8")),
        "canary_nonce_utf8_bytes": len(nonce.encode("utf-8")),
        "commission_id": capsule["commission_id"],
        "fence_token": transaction["fence_token"],
        "idempotency_key": transaction["idempotency_key"],
        "immutable_input_manifest_sha256": sha256_hex(input_bytes),
        "lease_id": transaction["lease_id"],
        "result_slot": SLOT,
        "result_txn_id": "result-po03-canary-001-1",
        "task_id": capsule["task_id"],
        "worker_id": WORKER_ID,
        "worker_role": "producer",
    }
    payload_bytes = canonical_payload(payload)

    document = {
        "canary_version": CANARY_VERSION,
        "canonical_json": {
            "document_serialization": {
                "encoding": "utf-8",
                "ensure_ascii": False,
                "indent": 2,
                "key_order": "sorted",
                "trailing_newline": True,
            },
            "document_sha256_recorded_in": MANIFEST_PATH,
            "hash_algorithm": "sha256",
            "payload_bytes": len(payload_bytes),
            "payload_serialization": {
                "encoding": "utf-8",
                "ensure_ascii": False,
                "key_order": "sorted",
                "separators": [",", ":"],
                "trailing_newline": False,
            },
            "payload_sha256": sha256_hex(payload_bytes),
        },
        "decision_changed": [],
        "derivation": {
            "acceptance_contract": CAPSULE_ACCEPTANCE,
            "emitter": f"{SLOT}/canary_tool.py",
            "input_capsule": CAPSULE_INPUT,
            "reproduce": f"python3 {SLOT}/canary_tool.py emit-canary --check",
        },
        "falsifiable_hypothesis": capsule["falsifiable_hypothesis"],
        "obzio_state_claim": {
            "claimed_by_producer": "READY_TO_COMMIT",
            "completion_actor": None,
            "independent_acceptance": "NOT_TESTED",
            "not_claimed": ["ACCEPTED", "COMPLETED"],
            "self_acceptance_performed": False,
        },
        "payload": payload,
        "supersedes": {
            "disposition": "SUPERSEDED_BY_CONTINUATION",
            "note": (
                "Attempt-1 canary bytes remain immutable evidence on commit "
                f"{PRIOR_ATTEMPT_COMMIT}; this continuation adds the logical worker id "
                "and canonical byte/hash metadata required by the task contract."
            ),
            "prior_canary_sha256": PRIOR_CANARY_SHA256,
            "prior_commit": PRIOR_ATTEMPT_COMMIT,
        },
    }
    return canonical_document(document)


def regenerate_from_ref(repo: Path, ref: str) -> bytes:
    return build_canary(blob_at(repo, ref, CAPSULE_INPUT), blob_at(repo, ref, CAPSULE_ACCEPTANCE))


def cmd_emit_canary(repo: Path, args: argparse.Namespace) -> int:
    target = repo / CANARY_PATH
    generated = build_canary(
        (repo / CAPSULE_INPUT).read_bytes(), (repo / CAPSULE_ACCEPTANCE).read_bytes()
    )
    if args.check:
        if not target.exists():
            print(f"CANARY_EMIT_CHECK_FAIL missing={CANARY_PATH}")
            return 1
        current = target.read_bytes()
        if current != generated:
            print(f"CANARY_EMIT_CHECK_FAIL path={CANARY_PATH} working_tree_differs_from_regeneration")
            return 1
        print(f"CANARY_EMIT_CHECK_PASS path={CANARY_PATH} sha256={sha256_hex(current)} bytes={len(current)}")
        return 0
    target.write_bytes(generated)
    print(f"CANARY_EMITTED path={CANARY_PATH} sha256={sha256_hex(generated)} bytes={len(generated)}")
    return 0


def cmd_build_manifest(repo: Path, args: argparse.Namespace) -> int:
    slot_dir = repo / SLOT
    artifacts: list[dict[str, Any]] = []
    total = 0
    for file_path in sorted(slot_dir.iterdir()):
        if not file_path.is_file() or file_path.name == "manifest.json":
            continue
        payload = file_path.read_bytes()
        total += len(payload)
        artifacts.append(
            {
                "artifact_id": file_path.stem.replace("_", "-"),
                "bytes": len(payload),
                "disposition": DISPOSITIONS.get(file_path.name, "CURRENT"),
                "logical_name": file_path.name,
                "media_type": media_type_for(file_path.name),
                "path": f"{SLOT}/{file_path.name}",
                "sha256": sha256_hex(payload),
            }
        )
    document = {
        "artifact_count": len(artifacts),
        "artifacts": artifacts,
        "commission_id": "COM-PO03-REPOSITORY-ENGINEERING-PORTABLE-RUNTIME-20260822-v001",
        "decision_changed": [],
        "fence_token": 1,
        "hash_algorithm": "sha256",
        "manifest_version": MANIFEST_VERSION,
        "result_slot": SLOT,
        "round": args.round,
        "self_entry": {
            "media_type": "application/json",
            "note": (
                "A manifest cannot embed its own digest; manifest.json bytes are hashed "
                "from the immutable commit in readback-receipt.json and in the worker return."
            ),
            "path": MANIFEST_PATH,
            "sha256": None,
        },
        "task_id": "po03-canary-001",
        "total_bytes": total,
        "verification_command": f"python3 {SLOT}/canary_tool.py verify --ref <commit-sha>",
        "worker_id": WORKER_ID,
    }
    (repo / MANIFEST_PATH).write_bytes(canonical_document(document))
    written = (repo / MANIFEST_PATH).read_bytes()
    print(
        f"MANIFEST_BUILT round={args.round} artifacts={len(artifacts)} total_bytes={total} "
        f"sha256={sha256_hex(written)} bytes={len(written)}"
    )
    return 0


def cmd_verify(repo: Path, args: argparse.Namespace) -> int:
    failures: list[str] = []
    commit = git(repo, "rev-parse", f"{args.ref}^{{commit}}").decode("utf-8").strip()
    print(f"PO03_CANARY_VERIFY ref={args.ref} commit={commit}")

    manifest = json.loads(blob_at(repo, commit, MANIFEST_PATH).decode("utf-8"))
    manifest_bytes = blob_at(repo, commit, MANIFEST_PATH)
    print(
        f"MANIFEST path={MANIFEST_PATH} round={manifest['round']} "
        f"sha256={sha256_hex(manifest_bytes)} bytes={len(manifest_bytes)}"
    )

    total = 0
    listed: set[str] = set()
    for artifact in manifest["artifacts"]:
        path = artifact["path"]
        listed.add(path)
        try:
            payload = blob_at(repo, commit, path)
        except subprocess.CalledProcessError:
            failures.append(f"missing blob {path}")
            print(f"ARTIFACT_FAIL path={path} reason=not_present_in_commit")
            continue
        digest = sha256_hex(payload)
        size = len(payload)
        total += size
        ok = digest == artifact["sha256"] and size == artifact["bytes"]
        if not ok:
            failures.append(f"digest/byte mismatch {path}")
        print(
            f"ARTIFACT_{'PASS' if ok else 'FAIL'} path={path} sha256={digest} bytes={size} "
            f"media_type={artifact['media_type']} disposition={artifact['disposition']}"
        )

    if total != manifest["total_bytes"] or len(manifest["artifacts"]) != manifest["artifact_count"]:
        failures.append("manifest totals disagree with artifacts")
        print(f"TOTALS_FAIL declared={manifest['total_bytes']}/{manifest['artifact_count']} observed={total}/{len(manifest['artifacts'])}")
    else:
        print(f"TOTALS_PASS artifact_count={manifest['artifact_count']} total_bytes={total}")

    tracked = set(tracked_at(repo, commit, SLOT))
    uncovered = sorted(tracked - listed - {MANIFEST_PATH})
    dangling = sorted(listed - tracked)
    if uncovered or dangling:
        failures.append("manifest coverage incomplete")
        print(f"COVERAGE_FAIL uncovered={uncovered} dangling={dangling}")
    else:
        print(f"COVERAGE_PASS tracked_in_slot={len(tracked)} listed_plus_manifest={len(listed) + 1}")

    committed_canary = blob_at(repo, commit, CANARY_PATH)
    regenerated = regenerate_from_ref(repo, commit)
    if committed_canary == regenerated:
        print(f"REGENERATION_PASS path={CANARY_PATH} sha256={sha256_hex(committed_canary)}")
    else:
        failures.append("canary.json is not reproducible from the immutable capsule")
        print(f"REGENERATION_FAIL path={CANARY_PATH} regenerated_sha256={sha256_hex(regenerated)}")

    canary = json.loads(committed_canary.decode("utf-8"))
    payload_bytes = canonical_payload(canary["payload"])
    meta = canary["canonical_json"]
    if sha256_hex(payload_bytes) == meta["payload_sha256"] and len(payload_bytes) == meta["payload_bytes"]:
        print(f"PAYLOAD_METADATA_PASS payload_sha256={meta['payload_sha256']} payload_bytes={meta['payload_bytes']}")
    else:
        failures.append("canary payload hash metadata does not match its payload")
        print("PAYLOAD_METADATA_FAIL")

    capsule = json.loads(blob_at(repo, commit, CAPSULE_INPUT).decode("utf-8"))
    nonce = canary["payload"]["canary_nonce"]
    if nonce == capsule["canary_nonce"]:
        print(f"NONCE_PASS canary_nonce={nonce} sha256={canary['payload']['canary_nonce_sha256']}")
    else:
        failures.append("canary nonce differs from the capsule nonce")
        print("NONCE_FAIL")

    if canary["payload"]["worker_id"] != WORKER_ID or canary["payload"]["fence_token"] != 1:
        failures.append("worker id or fence token incorrect")
        print("IDENTITY_FAIL")
    else:
        print(f"IDENTITY_PASS worker_id={WORKER_ID} fence_token=1")

    changed = [
        item.decode("utf-8")
        for item in git(repo, "diff", "--name-only", "-z", f"{commit}~{args.depth}", commit).split(b"\0")
        if item
    ]
    escaped = sorted(path for path in changed if not path.startswith(f"{SLOT}/"))
    if escaped:
        failures.append("writes escaped the owned result slot")
        print(f"PATH_SCOPE_FAIL escaped={escaped}")
    else:
        print(f"PATH_SCOPE_PASS depth={args.depth} changed_paths={len(changed)} all_within={SLOT}/")

    print(f"RESULT={'PASS' if not failures else 'FAIL'} failures={len(failures)}")
    for failure in failures:
        print(f"FAILURE {failure}")
    return 0 if not failures else 1


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    sub = parser.add_subparsers(dest="command", required=True)

    emit = sub.add_parser("emit-canary", help="write canary.json deterministically from the capsule")
    emit.add_argument("--check", action="store_true", help="compare instead of writing")

    manifest = sub.add_parser("build-manifest", help="write manifest.json over every slot artifact")
    manifest.add_argument("--round", type=int, required=True)

    verify = sub.add_parser("verify", help="verify committed bytes at an immutable commit")
    verify.add_argument("--ref", required=True)
    verify.add_argument("--depth", type=int, default=1, help="commits back to include in path-scope check")

    args = parser.parse_args(argv)
    repo = repo_root(Path(__file__).resolve().parent)
    try:
        if args.command == "emit-canary":
            return cmd_emit_canary(repo, args)
        if args.command == "build-manifest":
            return cmd_build_manifest(repo, args)
        return cmd_verify(repo, args)
    except (OSError, ValueError, KeyError, json.JSONDecodeError, subprocess.CalledProcessError) as exc:
        print(f"PO03_CANARY_ERROR: {exc}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
