#!/usr/bin/env python3
"""Score every generation on every frozen suite and emit the comparison document.

    python3 -I workstreams/po03/successor/score_generations.py --write
    python3 -I workstreams/po03/successor/score_generations.py --check

``--check`` re-runs the whole comparison and asserts the committed document is
byte-identical.  That is the executable form of "same suite, same inputs, same
command": if any generation, suite or reducer changes, the check fails and the
recorded score can no longer be passed off as current.

The document deliberately contains no timestamp, no path outside the repository
and no environment value, because a score that cannot be regenerated byte for
byte is a claim rather than evidence.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

PO03 = Path(__file__).resolve().parents[1]
REPO_ROOT = PO03.parents[1]
if str(PO03) not in sys.path:
    sys.path.insert(0, str(PO03))

from successor.harness import score as scoring  # noqa: E402
from successor.harness.controller_api import sha256_bytes  # noqa: E402
from successor.harness.runner import case_set_digest, load_cases, run_suite  # noqa: E402

MANIFEST = PO03 / "successor" / "suite" / "suite-manifest.json"
PREREGISTRATION = PO03 / "successor" / "suite" / "lift-preregistration.json"
OUTPUT = PO03 / "successor" / "scores" / "generation-comparison.json"


def load_generations() -> dict[str, Any]:
    from successor.g0 import controller as g0
    from successor.g1 import factory as g1

    generations: dict[str, Any] = {
        "G0": {
            "build": g0.build,
            "label": g0.G0Controller.generation_label,
            "provenance": g0.PROVENANCE,
            "source": "workstreams/po03/successor/g0/controller.py",
            "source_sha256": g0.digest_of_source(),
            "entry_point": "workstreams/po03/successor/g0/run.py",
        },
        "G1": {
            "build": g1.build,
            "label": g1.G1Controller.generation_label,
            "provenance": g1.PROVENANCE,
            "source": "workstreams/po03/successor/g1/factory.py",
            "source_sha256": g1.digest_of_source(),
            "entry_point": "workstreams/po03/successor/g1/run.py",
        },
    }
    try:
        from successor.g2 import successor as g2
    except ImportError:
        return generations
    generations["G2"] = {
        "build": g2.build,
        "label": g2.G2Controller.generation_label,
        "provenance": g2.PROVENANCE,
        "source": "workstreams/po03/successor/g2/successor.py",
        "source_sha256": g2.digest_of_source(),
        "entry_point": "workstreams/po03/successor/g2/run.py",
    }
    return generations


# Every holdout figure this document reports is provisional, and says so in the
# document rather than only in a commit message.  The holdout cases, attacks and
# expected outcomes are cohort a6's, authored before any producer branch was
# published, but they were *selected and bound* by the same owner that authored
# the generations being scored.  That is weaker independence than authorship by a
# non-author, and a perfect score on a suite the author assembled is exactly the
# result that most deserves a caveat.
HOLDOUT_INDEPENDENCE: dict[str, Any] = {
    "status": "PROVISIONAL",
    "applies_to": "every holdout figure in this document, including G2's 10/10, and the headline verdict, which is computed on the holdout suite",
    "why_provisional": (
        "The holdout cases were authored by cohort po03-worker-a6 without sight of any generation, but "
        "they were selected from a6's set and bound to executable operations by po03-worker-a8, the same "
        "owner that authored the generations. Selection and encoding by the generation author is weaker "
        "independence than authorship by a non-author, so a perfect holdout score cannot yet be read as "
        "a blind result."
    ),
    "pending": {
        "cohort": "a13",
        "model": "gpt-5.6-sol-xhigh",
        "design": (
            "at least twenty cases authored from the commission's acceptance criteria alone, frozen and "
            "pushed before reading anything of this cohort's, so neither selection nor encoding passes "
            "through the generation author"
        ),
        "supersedes_this_status_when": "a13's suite is published and the generations are scored against it",
    },
    "what_would_count_as_the_finding": (
        "If G2 scores materially lower on a13's blind suite than the 10/10 recorded here, that is the "
        "result, and it is more honest than a perfect score on a suite this cohort assembled. Nothing in "
        "this document should be read as predicting otherwise."
    ),
    "unaffected": (
        "The public-suite figures and the G0-to-G1 and G1-to-G2 public comparisons do not depend on the "
        "holdout, and the public suite was always this cohort's own and declared as such."
    ),
}


def load_suites() -> list[dict[str, Any]]:
    """Load every declared suite, refusing any whose bytes drifted from the freeze."""
    manifest = json.loads(MANIFEST.read_text(encoding="utf-8"))
    suites: list[dict[str, Any]] = []
    for entry in manifest["suites"]:
        path = REPO_ROOT / entry["path"]
        actual = sha256_bytes(path.read_bytes())
        if actual != entry["sha256"]:
            raise SystemExit(
                f"FROZEN SUITE DRIFT: {entry['path']} is {actual}, manifest declares {entry['sha256']}"
            )
        document, cases = load_cases(path)
        suites.append(
            {
                "key": entry["key"],
                "role": entry["role"],
                "path": entry["path"],
                "authored_by": entry["authored_by"],
                "file_sha256": actual,
                "case_set_id": document.get("case_set_id"),
                "case_semantic_digest": case_set_digest(cases),
                "cases": cases,
            }
        )
    return suites


def build_document() -> dict[str, Any]:
    preregistration = json.loads(PREREGISTRATION.read_text(encoding="utf-8"))
    suites = load_suites()
    generations = load_generations()

    scores: dict[str, Any] = {}
    for generation_id in sorted(generations):
        generation = generations[generation_id]
        suite_scores: dict[str, Any] = {}
        for suite in suites:
            records = run_suite(generation["build"], suite["cases"])
            summary = scoring.summarise(records)
            summary["case_table"] = scoring.case_table(records)
            suite_scores[suite["key"]] = summary
        scores[generation_id] = {
            "generation_id": generation_id,
            "label": generation["label"],
            "provenance": generation["provenance"],
            "source": generation["source"],
            "source_sha256": generation["source_sha256"],
            "entry_point": generation["entry_point"],
            "suites": suite_scores,
        }

    comparisons = []
    for pair in preregistration["comparisons"]:
        if pair["baseline"] not in scores or pair["candidate"] not in scores:
            comparisons.append(
                {
                    "verdict": "NOT_YET",
                    "suite": pair["suite"],
                    "baseline": pair["baseline"],
                    "candidate": pair["candidate"],
                    "reason": "one generation in this comparison is not present in the committed tree",
                    "conditions": [],
                    "unmet_conditions": [],
                }
            )
            continue
        comparisons.append(
            scoring.compare(
                scores,
                baseline=pair["baseline"],
                candidate=pair["candidate"],
                preregistration=preregistration,
                suite_key=pair["suite"],
            )
        )

    headline = next(
        (
            comparison
            for comparison in comparisons
            if comparison["baseline"] == preregistration["primary_comparison"]["baseline"]
            and comparison["candidate"] == preregistration["primary_comparison"]["candidate"]
            and comparison["suite"] == preregistration["primary_comparison"]["suite"]
        ),
        None,
    )

    return {
        "document_id": "po03-a8-generation-comparison-v001",
        "commission_id": "COM-PO03-REPOSITORY-ENGINEERING-PORTABLE-RUNTIME-20260822-v001",
        "produced_by": "po03-worker-a8",
        "consumed_by": "po03-worker-a7 (owner of workstreams/po03/metrics/generation-comparison.json)",
        "command": "python3 -I workstreams/po03/successor/score_generations.py --check",
        "reproducibility": "document contains no timestamp or environment value; --check asserts byte identity",
        "preregistration": {
            "path": "workstreams/po03/successor/suite/lift-preregistration.json",
            "sha256": sha256_bytes(PREREGISTRATION.read_bytes()),
            "metric_id": preregistration["primary_metric"]["metric_id"],
            "frozen_at_commit": preregistration["frozen_at_commit"],
        },
        "suites": [
            {
                "key": suite["key"],
                "role": suite["role"],
                "path": suite["path"],
                "authored_by": suite["authored_by"],
                "file_sha256": suite["file_sha256"],
                "case_set_id": suite["case_set_id"],
                "case_semantic_digest": suite["case_semantic_digest"],
                "case_count": len(suite["cases"]),
            }
            for suite in suites
        ],
        "generations": scores,
        "comparisons": comparisons,
        "holdout_independence": HOLDOUT_INDEPENDENCE,
        "headline": {
            "metric_id": preregistration["primary_metric"]["metric_id"],
            "baseline": preregistration["primary_comparison"]["baseline"],
            "candidate": preregistration["primary_comparison"]["candidate"],
            "suite": preregistration["primary_comparison"]["suite"],
            "verdict": headline["verdict"] if headline else "NOT_YET",
            "lift": headline.get("lift") if headline else None,
            "reason": headline["reason"] if headline else "primary comparison unavailable",
            "result_status": "PROVISIONAL",
            "provisional_because": HOLDOUT_INDEPENDENCE["why_provisional"],
        },
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--write", action="store_true")
    group.add_argument("--check", action="store_true")
    group.add_argument("--print", dest="show", action="store_true")
    args = parser.parse_args()

    document = build_document()
    text = json.dumps(document, indent=2, sort_keys=True, ensure_ascii=False) + "\n"

    if args.show:
        for generation_id, score in document["generations"].items():
            for suite_key, summary in score["suites"].items():
                print(
                    f"{generation_id:3s} {suite_key:8s} "
                    f"pass={summary['cases_passed']}/{summary['cases_total']} "
                    f"rate={summary['pass_rate']} "
                    f"critical={summary['critical_pass_rate']} "
                    f"false_completions={summary['false_completion_count']}"
                )
                if summary["failed_cases"]:
                    print(f"      failed: {', '.join(summary['failed_cases'])}")
        for comparison in document["comparisons"]:
            print(
                f"{comparison['baseline']}->{comparison['candidate']} on {comparison['suite']}: "
                f"{comparison['verdict']} lift={comparison.get('lift')} {comparison['reason']}"
            )
        return 0

    if args.check:
        if not OUTPUT.is_file():
            print(f"MISSING {OUTPUT}")
            return 1
        if OUTPUT.read_text(encoding="utf-8") != text:
            print(f"DRIFTED {OUTPUT}: recomputed scores differ from the committed document")
            return 1
        print(f"REPRODUCED {OUTPUT} sha256={sha256_bytes(text.encode('utf-8'))}")
        return 0

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(text, encoding="utf-8")
    print(f"WROTE {OUTPUT} sha256={sha256_bytes(text.encode('utf-8'))}")
    print(f"HEADLINE {document['headline']['verdict']} lift={document['headline']['lift']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
