#!/usr/bin/env python3
"""Re-anchor the seed's citation digests to the bytes now on disk, visibly.

This is the tool DEF-SCP-01 says the estate needs and does not have, restricted
to the one place this lane owns: its own chain seed. It does NOT decide that a
mismatch is benign. It reports every citation whose digest moved, and — this is
the part that makes it a re-anchor rather than a rubber stamp — walks git history
for each moved artifact to establish that the recorded digest was correct at some
commit on this branch. A citation whose digest was never correct anywhere is
refused and left alone, because that is not supersession, it is a digest that
never described the file.

Why this is needed at all: two cited artifacts are regenerated by other tools in
this lane — the regression rerun report carries a produced_at, and the concurrency
observation reads the clock and the remote. Their bytes legitimately move. The
alternative to re-anchoring is to never re-run a regression suite after seeding,
which is a worse rule.

Standard library only. Runs under `python3 -I`.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[7]
SEED = (Path(__file__).resolve().parents[1]
        / "chains/SCP-B-CHAIN-SEED-20260827-v001.json")
RECEIPT = REPO_ROOT / "receipts/so02/2026-08-27/scp-b/reproductions/CITATION-REANCHOR.json"


def sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def blob_at(commit: str, path: str) -> bytes | None:
    done = subprocess.run(["git", "show", f"{commit}:{path}"],
                          cwd=str(REPO_ROOT), capture_output=True)
    return done.stdout if done.returncode == 0 else None


def commits_touching(path: str) -> list[str]:
    done = subprocess.run(["git", "log", "--format=%H", "--", path],
                          cwd=str(REPO_ROOT), capture_output=True, text=True)
    return done.stdout.split() if done.returncode == 0 else []


def was_correct_at(path: str, digest: str) -> str | None:
    """The commit at which the recorded digest described this file, if any."""
    for commit in commits_touching(path):
        blob = blob_at(commit, path)
        if blob is not None and sha256_bytes(blob) == digest:
            return commit
    return None


def citations(seed: dict[str, Any]):
    for chain in seed["chains"]:
        for node in chain["nodes"]:
            for citation in node.get("evidence_citations", []):
                if citation.get("artifact_path") and citation.get("sha256"):
                    yield chain["chain_id"], node["node_id"], citation


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--apply", action="store_true",
                        help="write the re-anchored digests; without it, report only")
    args = parser.parse_args(argv)

    seed = json.loads(SEED.read_text(encoding="utf-8"))
    matched, superseded, refused, missing = [], [], [], []

    for chain_id, node_id, citation in citations(seed):
        path = citation["artifact_path"]
        recorded = citation["sha256"]
        target = REPO_ROOT / path
        if not target.is_file():
            missing.append({"chain_id": chain_id, "node_id": node_id, "artifact_path": path})
            continue
        actual = sha256_bytes(target.read_bytes())
        if actual == recorded:
            matched.append(path)
            continue
        anchor = was_correct_at(path, recorded)
        record = {
            "chain_id": chain_id,
            "node_id": node_id,
            "artifact_path": path,
            "recorded_sha256": recorded,
            "worktree_sha256": actual,
            "recorded_digest_was_correct_at_commit": anchor[:8] if anchor else None,
        }
        if anchor:
            record["classification"] = "EVIDENCE_SUPERSEDED"
            record["action"] = "re-anchor to the worktree digest"
            superseded.append(record)
            if args.apply:
                citation["sha256"] = actual
                citation["reanchored"] = {
                    "from": recorded,
                    "was_correct_at_commit": anchor[:8],
                    "reason": "the artifact is regenerated by a tool in this lane and "
                              "moved under an authorised write",
                }
        else:
            record["classification"] = "EVIDENCE_HASH_MISMATCH"
            record["action"] = "refused; left unchanged for a human to look at"
            record["why"] = ("the recorded digest was not correct at any commit that "
                             "touched this path, so this is not supersession")
            refused.append(record)

    report = {
        "record_id": "SCP-B-CITATION-REANCHOR-20260827-v001",
        "produced_at": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "decision_changed": [],
        "instrument": "workstreams/so02/control-plane/operating-environment/scp-si-01/"
                      "lane-b/tools/reanchor_seed_citations.py",
        "seed": str(SEED.relative_to(REPO_ROOT)),
        "applied": args.apply,
        "citations_examined": len(matched) + len(superseded) + len(refused) + len(missing),
        "matched": len(matched),
        "superseded_and_reanchored": superseded,
        "refused_as_genuine_mismatch": refused,
        "cited_artifact_missing": missing,
        "method": (
            "For each citation whose digest no longer matches the worktree, walk this "
            "branch's history for that path and look for a commit at which the recorded "
            "digest was correct. Found means the artifact was superseded by an authorised "
            "write and the citation is re-anchored. Not found means the digest never "
            "described the file, which is refused rather than re-anchored."
        ),
        "scope_limit": (
            "This applies the DEF-SCP-01 distinction to this lane's own chain seed only. "
            "It does not touch the l4 workstream ledger and does not change any finding "
            "code in currentctl.py. That mechanism change remains PENDING and routed, and "
            "is seeded as ICH-07."
        ),
        "evidence_label": "DIRECTLY_REPRODUCED",
        "provenance_class": "EARNED",
        "provenance_basis": "DEF-SCP-01, and the two citations in this lane's own seed "
                            "that went stale because the artifacts they cite are "
                            "regenerated by tools in this lane.",
    }

    if args.apply:
        SEED.write_text(json.dumps(seed, indent=2) + "\n", encoding="utf-8")
        RECEIPT.parent.mkdir(parents=True, exist_ok=True)
        RECEIPT.write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8")

    print(json.dumps({
        "applied": args.apply,
        "examined": report["citations_examined"],
        "matched": len(matched),
        "superseded_reanchored": len(superseded),
        "refused": len(refused),
        "missing": len(missing),
        "superseded_paths": sorted({r["artifact_path"] for r in superseded}),
        "refused_paths": sorted({r["artifact_path"] for r in refused}),
    }, indent=2))
    return 1 if (refused or missing) else 0


if __name__ == "__main__":
    sys.exit(main())
